//Testar as requisições - Schema Cliente
@baseUrl = http://localhost:3000


###
// POST contratos
POST {{baseUrl}}/contratos
Content-Type: application/json

{
    "nome": "NETServ",
    "descricao": "Link Dedicado Internet de 100 MB",
    "numeroNota": "49371",
    "valor": "4040.00",
    "dataEmissao": "2019-10-02",
    "dataAssinatura": "2019-10-04",
    "dataVencimento": "2019-10-20"
}

###
// GET contratos
GET {{baseUrl}}/contratos
###
// GET contratos/:id
@id = 5d9bc1a19787521c4432c939
GET {{baseUrl}}/contratos/{{id}}

###
// GET contratos/:texto
@texto = nonius
GET {{baseUrl}}/contratos/texto/{{texto}}

###
// PUT /contratos/:id
@idUpdate = 5d9bce2ed4ddba0dec8b0530
PUT {{baseUrl}}/contratos/{{idUpdate}}
Content-Type: application/json

{
    "nome": "Alterando Contrato",
    "descricao": "A descrição do contrato foi alterada",
    "numeroNota": "45678",
    "valor": "14539.68",
    "dataEmissao": "2019-10-22",
    "dataAssinatura": "2019-10-23",
    "dataVencimento": "2019-11-10"
}
###
// DELETE contratos/:id
@idDelete = 5d9bd0eed4ddba0dec8b0531
DELETE {{baseUrl}}/contratos/{{idDelete}}