//Testar as requisições - Schema Cliente
@baseUrl = http://localhost:3000


###
// POST contratos
POST {{baseUrl}}/contratos
Content-Type: application/json

{
    "nome": "Embratel Dados",
    "descricao": "Link Dedicado Internet de 300 MB",
    "numeroNota": "45678",
    "valor": "14539.68",
    "dataEmissao": "2019-10-20",
    "dataAssinatura": "2019-10-20",
    "dataVencimento": "2019-11-05"
}

###
// GET contratos
GET {{baseUrl}}/contratos
###
// GET contratos/:id
@id = 5d9bc1a19787521c4432c939
GET {{baseUrl}}/contratos/{{id}}

###
// GET contratos/:texto
@texto = dedicado
GET {{baseUrl}}/contratos/texto/{{texto}}

###
// PUT /contratos/:id
@idUpdate = 5d9bbb2109a70d10b0824e7e
PUT {{baseUrl}}/contratos/{{idUpdate}}
Content-Type: application/json

{
    "nome": "Alterando Contrato",
    "descricao": "A descrição do contrato foi alterada",
    "numeroNota": "45678",
    "valor": "14539.68",
    "dataEmissao": "2019-10-22",
    "dataAssinatura": "2019-10-23",
    "dataVencimento": "2019-11-10"
}
###
// DELETE contratos/:id
@idDelete = 5d9bc1969787521c4432c937
DELETE {{baseUrl}}/contratos/{{idDelete}}